import Link from "next/link";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import Playground from "@/components/Playground";
import { PLANS } from "@/lib/plans";
import { appUrl } from "@/lib/stripe";

const EXAMPLE_URL =
  "/api/og?template=gradient&title=Ship%20social%20cards%20without%20a%20designer&subtitle=One%20GET%20request.%20A%20perfect%201200%C3%97630%20image%20for%20every%20page.&site=ogsmith.app";

const FEATURES: Array<{ title: string; body: string }> = [
  {
    title: "One GET request",
    body: "No SDK required. Point your <meta property=\"og:image\"> at a URL and you're done — works from any language or framework.",
  },
  {
    title: "Fast and serverless",
    body: "Images render in milliseconds with satori — no headless browser, no queue. Responses are CDN-cached so repeat crawls are free.",
  },
  {
    title: "Beautiful templates",
    body: "Four hand-tuned templates with themes and accent colors. Legible typography at any title length, tuned for social feeds.",
  },
  {
    title: "Usage you can predict",
    body: "Simple monthly render quotas. No overage surprises — when you're near the limit you'll see it on your dashboard.",
  },
];

export default function Home() {
  const base = appUrl().replace(/\/$/, "");
  return (
    <>
      <Nav />
      <main>
        {/* Hero */}
        <section className="mx-auto max-w-6xl px-4 pb-16 pt-16 text-center sm:px-6 sm:pt-20">
          <p className="mx-auto mb-4 w-fit rounded-full border border-indigo-500/40 bg-indigo-500/10 px-4 py-1 text-sm text-indigo-300">
            Open Graph images as an API
          </p>
          <h1 className="mx-auto max-w-3xl text-3xl font-bold leading-tight tracking-tight sm:text-5xl lg:text-6xl">
            Social cards for every page,{" "}
            <span className="text-indigo-400">from one URL</span>
          </h1>
          <p className="mx-auto mt-6 max-w-2xl text-lg text-zinc-400">
            Stop shipping pages with blank link previews. OGsmith renders
            pixel-perfect 1200×630 Open Graph images on demand — no headless
            browser, no design tool, no build step.
          </p>
          <div className="mt-8 flex flex-col items-stretch gap-3 sm:flex-row sm:justify-center sm:gap-4">
            <Link
              href="/signup"
              className="rounded-lg bg-indigo-600 px-6 py-3 text-center font-medium text-white hover:bg-indigo-500"
            >
              Get your free API key
            </Link>
            <Link
              href="/docs"
              className="rounded-lg border border-zinc-700 px-6 py-3 text-center font-medium text-zinc-300 hover:border-zinc-500"
            >
              Read the docs
            </Link>
          </div>
          <div className="mx-auto mt-12 max-w-3xl overflow-hidden rounded-xl border border-zinc-800 shadow-2xl shadow-indigo-500/10">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={EXAMPLE_URL}
              alt="Example Open Graph card generated by OGsmith"
              width={1200}
              height={630}
              className="w-full"
            />
          </div>
          <code className="mx-auto mt-4 block w-fit max-w-full overflow-x-auto whitespace-nowrap rounded-lg border border-zinc-800 bg-zinc-900 px-4 py-2 text-xs text-emerald-400">
            &lt;meta property=&quot;og:image&quot;
            content=&quot;{base}/api/og?title=...&quot; /&gt;
          </code>
        </section>

        {/* Features */}
        <section className="border-t border-zinc-800 bg-zinc-950 py-20">
          <div className="mx-auto grid max-w-6xl gap-8 px-4 sm:grid-cols-2 sm:px-6">
            {FEATURES.map((f) => (
              <div
                key={f.title}
                className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-4 sm:p-6"
              >
                <h3 className="mb-2 font-semibold text-white">{f.title}</h3>
                <p className="text-sm leading-relaxed text-zinc-400">{f.body}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Playground */}
        <section className="border-t border-zinc-800 py-20">
          <div className="mx-auto max-w-6xl px-4 sm:px-6">
            <h2 className="mb-2 text-3xl font-bold">Try it live</h2>
            <p className="mb-10 text-zinc-400">
              Tweak the parameters and render a real image from the API.
            </p>
            <Playground />
          </div>
        </section>

        {/* Pricing teaser */}
        <section className="border-t border-zinc-800 bg-zinc-950 py-20">
          <div className="mx-auto max-w-6xl px-4 text-center sm:px-6">
            <h2 className="mb-2 text-3xl font-bold">Simple pricing</h2>
            <p className="mb-10 text-zinc-400">
              Start free. Upgrade when your traffic does.
            </p>
            <div className="grid gap-6 sm:grid-cols-3">
              {Object.values(PLANS).map((plan) => (
                <div
                  key={plan.id}
                  className={`rounded-xl border p-6 text-left ${
                    plan.id === "pro"
                      ? "border-indigo-500 bg-indigo-500/5"
                      : "border-zinc-800 bg-zinc-900/50"
                  }`}
                >
                  <h3 className="font-semibold">{plan.name}</h3>
                  <p className="mt-2 text-3xl font-bold">
                    ${plan.priceMonthlyUsd}
                    <span className="text-base font-normal text-zinc-500">/mo</span>
                  </p>
                  <p className="mt-3 text-sm text-zinc-400">
                    {plan.monthlyRenders.toLocaleString()} renders / month
                    {plan.watermark ? " · watermarked" : " · no watermark"}
                  </p>
                </div>
              ))}
            </div>
            <Link
              href="/pricing"
              className="mt-8 inline-block rounded-lg border border-zinc-700 px-6 py-3 font-medium text-zinc-300 hover:border-zinc-500"
            >
              Compare plans
            </Link>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
